{
  "ok": false,
  "flag": 0,
  "score": 0,
  "reason": "error:HTTPConnectionPool(host='127.0.0.1', port=6002): Max retries exceeded with url: /check (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2e4692ec90>: Failed to establish a new connection: [Errno 111] Connection refused'))",
  "query_id": "QX-c6981e65",
  "module": "anomaly_detector",
  "domain": "testlogin.xyz"
}